development: &default
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  app_id: APP-80W284485P519543T
  # http_timeout: 30
  mode: sandbox
  sandbox_email_address: Platform.sdk.seller@gmail.com


test:
  <<: *default


production:
  mode: live
  username: admin_api1.vitrineonline.com
  password: DKJVG8KMXTBFWZFT
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AWU78If4EWNK1xJLuqvuBIF7s3dY
  app_id: APP-8TU98166249274123







