  test:
    # <<: *default
  # verbose_logging: true

  development:
    # <<: *default

  production:   
  mode: live
 
  # Credentials for REST APIs
  client_id: Abkh6ZginWQ3UPu22C0JNT5lh6nivSJdgi83dB4UULnxTNxA4lFlCsHUwBtBo6ywimJtwApythzi79Le
  client_secret: EMTfumeHWt6wurQqOQEc6hQNDPWWTotxCK69jd4MTefsJAKzLKJ_tx-4J8DhGQt4CelJJ5TOTuGG1puI
  # Mode can be 'live' or 'sandbox'
    # Credentials for Classic APIs
  app_id: Abkh6ZginWQ3UPu22C0JNT5lh6nivSJdgi83dB4UULnxTNxA4lFlCsHUwBtBo6ywimJtwApythzi79Le
  username: calixtodaniel_api1.gmail.com
  password: DSG2N7ZTJELQUNWL
  signature: ApTm-PAyPlvJvccJvw3u97zEAvNNAKnr2ZdPlbdLvJvW9XEWP2Rr3Csv
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  #sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/


