development:
  environment: "sandbox"
  username: calixtodaniel_api1.mail.com
  password: 1364777408
  signature: Alpha6L.-43wFwnp9zm0AdY3eaAhA8n5vJSYNiu00SlS0E62Stoo6v4c
  application_id: "APP-80W284485P519543T"
  #api_cert_file: "/path/to_cert"

test:
  environment: "sandbox"
  username: calixtodaniel_api1.mail.com
  password: 1364777408
  signature: Alpha6L.-43wFwnp9zm0AdY3eaAhA8n5vJSYNiu00SlS0E62Stoo6v4c
  application_id: "APP-80W284485P519543T"
  #api_cert_file: "/path/to_cert"



#production:
#  environment: "sandbox"
#  username: calixtodaniel_api1.mail.com
#  password: 1364777408
#  signature: Alpha6L.-43wFwnp9zm0AdY3eaAhA8n5vJSYNiu00SlS0E62Stoo6v4c
 # application_id: "APP-80W284485P519543T"
  #api_cert_file: "/path/to_cert"


production:
  environment: "production"
  username: calixtodaniel_api1.gmail.com
  password: DSG2N7ZTJELQUNWL
  signature: ApTm-PAyPlvJvccJvw3u97zEAvNNAKnr2ZdPlbdLvJvW9XEWP2Rr3Csv
  application_id: "Ac0YLy7fG3AfnmIYVNU7s8BofHgOCan60YdzB_r5Ii3glbU2A0gxaDvBlTqsDlDOrmWK8gcojx-uGiPw"
  #api_cert_file: "/path/to_cert"

