production:
  
  mode: live
  app_id: APP-8TU98166249274123
  username: admin_api1.vitrineonline.com
  password: DKJVG8KMXTBFWZFT
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AWU78If4EWNK1xJLuqvuBIF7s3dY






