test: &default

  # Credentials for REST APIs
  client_id: Adm-yjdv0q8Mi8XzvFxvlg4vvMGBXFtV2c-wzevyiKLLG_TVE2ySEErYsai2LQRp82cnvLJ-pX-RagtK
  client_secret: EF6yruPmH5KiUWp_RwerFUq4428q6qcXwf_Kj5fK3xlYi2zr7U65a2FLmTjb8Xa7jR-0NNizbICGirmO

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: admin_api1.vitrineonline.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: admin-facilitator@vitrineonline.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: live
  app_id: APP-8TU98166249274123
  username: admin_api1.vitrineonline.com
  password: 8CYZME3C4YAEJVD2
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31Ak0xPIy-QieczmS5X.b6k8jLOC8A
