development:
  environment: "sandbox"
  username: "sandbox_username"
  password: "sandbox_password"
  signature: "sandbox_signature"
  application_id: "sandbox_app_id"
  #api_cert_file:

test:
  environment: "sandbox"
  username: "sandbox_username"
  password: "sandbox_password"
  signature: "sandbox_signature"
  application_id: "sandbox_app_id"
  #api_cert_file: "/path/to_cert"

production:
  environment: "production"
  username: "admin_api1.vitrineonline.com"
  password: "8CYZME3C4YAEJVD2"
  signature: "AFcWxV21C7fd0v3bYYYRCpSSRl31Ak0xPIy-QieczmS5X.b6k8jLOC8A"
  application_id: "APP-8TU98166249274123"

  #api_cert_file: "/path/to_cert"




