development: &default

  # Credentials for REST APIs
  #client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  #client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox
  app_id: APP-80W284485P519543T
  username: contato_paypal_api1.vitrineonline.com
  password: RVPUV7CCQTBNW2WM
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AlSGupNbH5aLBBuAMSlTB5Gd87v5
  sandbox_email_address: contato_paypal_api1.vitrineonline.com


test:
  <<: *default
  mode: sandbox



production:
  <<: *default
  mode: sandbox
# app_id: APP-8TU98166249274123
#  username: admin_api1.vitrineonline.com
#  password: 8CYZME3C4YAEJVD2
# signature: AFcWxV21C7fd0v3bYYYRCpSSRl31Ak0xPIy-QieczmS5X.b6k8jLOC8A
