development: &default
  username: admin_api1.vitrineonline.com
  password: DKJVG8KMXTBFWZFT
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AWU78If4EWNK1xJLuqvuBIF7s3dY
  app_id: APP-8TU98166249274123
  # http_timeout: 30
  mode: sandbox
  sandbox_email_address: Platform.sdk.seller@gmail.com


test:
  <<: *default


production:
  <<: *default
  mode: live
  username: admin_api1.vitrineonline.com
  password: DKJVG8KMXTBFWZFT
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AWU78If4EWNK1xJLuqvuBIF7s3dY
  app_id: APP-8TU98166249274123







