test: &default

  # Credentials for REST APIs
  # client_id: Abkh6ZginWQ3UPu22C0JNT5lh6nivSJdgi83dB4UULnxTNxA4lFlCsHUwBtBo6ywimJtwApythzi79Le
  #client_secret: EMTfumeHWt6wurQqOQEc6hQNDPWWTotxCK69jd4MTefsJAKzLKJ_tx-4J8DhGQt4CelJJ5TOTuGG1puI

  # Mode can be 'live' or 'sandbox'
  # mode: live

  # Credentials for Classic APIs
  app_id: APP-8TU98166249274123
  username: admin_api1.vitrineonline.com
  password: DKJVG8KMXTBFWZFT
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31AWU78If4EWNK1xJLuqvuBIF7s3dY
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  #sandbox_email_address:  calixtodaniel@mail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

  development:
  <<: *default

  production:
  <<: *default
  mode: live





